/**
 * Field-spec definitions for every AVISION ONE CMS entity.
 * Every admin route imports its spec from here and passes to EntityScreen.
 * This keeps admin routes ~5 lines each.
 */
import type { FieldSpec } from './EntityScreen';

const F = {
  name: { key: 'name', label: 'Name', type: 'text', required: true, colSpan: 1 } as FieldSpec,
  title: { key: 'title', label: 'Title', type: 'text', required: true, colSpan: 1 } as FieldSpec,
  slug: { key: 'slug', label: 'Slug (URL)', type: 'text', help: 'Leave blank to auto-generate', colSpan: 1 } as FieldSpec,
  description: { key: 'description', label: 'Description', type: 'textarea', colSpan: 2 } as FieldSpec,
  image: (k = 'image', label = 'Image URL') => ({ key: k, label, type: 'image', placeholder: 'https://…', colSpan: 1 } as FieldSpec),
  displayOrder: { key: 'display_order', label: 'Display order', type: 'number', colSpan: 1 } as FieldSpec,
  active: { key: 'active', label: 'Active', type: 'bool', colSpan: 1 } as FieldSpec,
  visibility: { key: 'visibility', label: 'Visibility', type: 'visibility' } as FieldSpec,
  seo: { key: 'seo', label: 'SEO {title, desc, keywords}', type: 'json', help: 'JSON object', placeholder: '{"title": "...", "desc": "...", "keywords": ["…"]}', colSpan: 2 } as FieldSpec,
};

export const SPECS: Record<string, { title: string; subtitle?: string; icon?: any; fields: FieldSpec[]; extraColumns?: any; primaryLabel?: string; helpNote?: string; clientBadge?: 'app' | 'website' | 'both' }> = {
  // ==================== ACADEMIC ====================
  exam_categories_cms: {
    title: 'Exam Categories', icon: 'trophy', clientBadge: 'both',
    helpNote: 'Master list of exam categories (Banking, SSC, UPSC, etc.). Consumed by App tabs and Website navigation.',
    fields: [F.name, F.slug, F.description, F.image('icon', 'Icon key'), F.image('banner_image', 'Banner image URL'),
             { key: 'color', label: 'Accent color', type: 'text', placeholder: '#0B4DB8', colSpan: 1 },
             F.displayOrder, F.visibility, F.seo, F.active],
    extraColumns: [{ key: 'slug', label: 'Slug' }],
  },
  exams_cms: {
    title: 'Exams', icon: 'ribbon', clientBadge: 'both',
    helpNote: 'Individual exams (SBI PO, SSC CGL, etc.). Feeds Exam Info pages on Website and Test Prime filters on App.',
    fields: [F.name, F.slug,
             { key: 'category_id', label: 'Category ID', type: 'text', required: true, placeholder: 'banking', colSpan: 1 },
             F.image('banner_image', 'Banner image'), F.description,
             { key: 'eligibility', label: 'Eligibility', type: 'textarea', colSpan: 2 },
             { key: 'exam_pattern', label: 'Exam pattern (JSON)', type: 'json', colSpan: 2 },
             { key: 'syllabus', label: 'Syllabus (JSON)', type: 'json', colSpan: 2 },
             { key: 'important_dates', label: 'Important dates (JSON)', type: 'json', colSpan: 2 },
             F.seo, F.visibility, F.displayOrder, F.active],
    extraColumns: [{ key: 'category_id', label: 'Category' }],
  },
  subjects: {
    title: 'Subjects', icon: 'book', clientBadge: 'both',
    helpNote: 'Master list of subjects (Quantitative Aptitude, Reasoning, English, GK). Used by Video Courses curriculum + Test Prime chapters.',
    fields: [F.name, { key: 'code', label: 'Code', type: 'text', colSpan: 1 },
             { key: 'color', label: 'Color', type: 'text', colSpan: 1 },
             F.image('icon', 'Icon key'), F.description,
             { key: 'exam_ids', label: 'Applicable exam IDs', type: 'chips', help: 'Which exams use this subject', colSpan: 2 },
             F.displayOrder, F.active],
  },
  chapters: {
    title: 'Chapters', icon: 'list', clientBadge: 'both',
    helpNote: 'Chapters within a subject. Auto-referenced by Lessons + Video lectures.',
    fields: [F.name,
             { key: 'subject_id', label: 'Subject ID', type: 'text', required: true, colSpan: 1 },
             { key: 'difficulty', label: 'Difficulty', type: 'select', options: [{ label: 'Easy', value: 'easy' }, { label: 'Medium', value: 'medium' }, { label: 'Hard', value: 'hard' }], colSpan: 1 },
             { key: 'estimated_hours', label: 'Est. hours', type: 'number', colSpan: 1 },
             F.description, F.displayOrder, F.active],
    extraColumns: [{ key: 'subject_id', label: 'Subject' }, { key: 'difficulty', label: 'Difficulty' }],
  },
  lessons: {
    title: 'Lessons', icon: 'play-circle', clientBadge: 'both',
    helpNote: 'Individual lessons/lectures. Reusable across video courses and study material.',
    fields: [F.title,
             { key: 'chapter_id', label: 'Chapter ID', type: 'text', required: true, colSpan: 1 },
             { key: 'subject_id', label: 'Subject ID', type: 'text', colSpan: 1 },
             { key: 'type', label: 'Type', type: 'select', options: [{ label: 'Video', value: 'video' }, { label: 'PDF', value: 'pdf' }, { label: 'Quiz', value: 'quiz' }, { label: 'Text', value: 'text' }], colSpan: 1 },
             { key: 'duration_min', label: 'Duration (min)', type: 'number', colSpan: 1 },
             { key: 'video_url', label: 'Video URL', type: 'url', colSpan: 2 },
             { key: 'pdf_url', label: 'PDF URL', type: 'url', colSpan: 2 },
             { key: 'content', label: 'Content (Markdown)', type: 'textarea', colSpan: 2 },
             { key: 'is_free', label: 'Is free preview', type: 'bool', colSpan: 1 },
             F.displayOrder, F.active],
    extraColumns: [{ key: 'chapter_id', label: 'Chapter' }, { key: 'type', label: 'Type' }],
  },

  // ==================== LEARNING CONTENT ====================
  question_bank: {
    title: 'Question Bank', icon: 'help-circle', clientBadge: 'app',
    helpNote: 'Central question bank for Test Prime. Options in JSON array, correct = 0-indexed integer.',
    fields: [{ key: 'text', label: 'Question', type: 'textarea', required: true, colSpan: 2 },
             { key: 'options', label: 'Options (JSON array)', type: 'json', required: true, placeholder: '["A", "B", "C", "D"]', colSpan: 2 },
             { key: 'correct', label: 'Correct index', type: 'number', colSpan: 1 },
             { key: 'marks', label: 'Marks', type: 'number', colSpan: 1 },
             { key: 'negative_marks', label: 'Negative marks', type: 'number', colSpan: 1 },
             { key: 'difficulty', label: 'Difficulty', type: 'select', options: [{ label: 'Easy', value: 'easy' }, { label: 'Medium', value: 'medium' }, { label: 'Hard', value: 'hard' }], colSpan: 1 },
             { key: 'subject', label: 'Subject', type: 'text', colSpan: 1 },
             { key: 'topic', label: 'Topic', type: 'text', colSpan: 1 },
             { key: 'language', label: 'Language', type: 'select', options: [{ label: 'English', value: 'en' }, { label: 'Hindi', value: 'hi' }, { label: 'Bilingual', value: 'both' }], colSpan: 1 },
             { key: 'explanation', label: 'Explanation', type: 'textarea', colSpan: 2 },
             { key: 'exam_ids', label: 'Applicable exams', type: 'chips', colSpan: 2 },
             F.active],
    primaryLabel: 'text',
    extraColumns: [{ key: 'subject', label: 'Subject' }, { key: 'difficulty', label: 'Difficulty' }],
  },
  study_material_v2: {
    title: 'Study Material', icon: 'document-text', clientBadge: 'both',
    helpNote: 'PDFs, notes, cheatsheets, formula books. Attach to products or exams for entitled-user delivery.',
    fields: [F.title, { key: 'type', label: 'Type', type: 'select', options: [{ label: 'PDF', value: 'pdf' }, { label: 'Notes', value: 'notes' }, { label: 'Formula', value: 'formula' }, { label: 'Cheatsheet', value: 'cheatsheet' }, { label: 'Video', value: 'video' }], required: true, colSpan: 1 },
             { key: 'subject_id', label: 'Subject ID', type: 'text', colSpan: 1 },
             { key: 'exam_ids', label: 'Applicable exams', type: 'chips', colSpan: 2 },
             { key: 'product_ids', label: 'Attached to products', type: 'chips', help: 'Only users entitled to these products can access', colSpan: 2 },
             F.description, F.image('url', 'File URL (PDF/MP4/etc)'), F.image('thumbnail', 'Thumbnail'),
             { key: 'language', label: 'Language', type: 'text', colSpan: 1 },
             { key: 'is_free', label: 'Is free', type: 'bool', colSpan: 1 },
             F.visibility, F.displayOrder, F.active],
    extraColumns: [{ key: 'type', label: 'Type' }, { key: 'subject_id', label: 'Subject' }],
  },
  current_affairs: {
    title: 'Current Affairs', icon: 'newspaper', clientBadge: 'both',
    helpNote: 'Daily articles surfaced on App home + Website blog. Auto-tagged for category filters.',
    fields: [F.title, F.slug, { key: 'category', label: 'Category', type: 'text', placeholder: 'economy | polity | international', colSpan: 1 },
             { key: 'tags', label: 'Tags', type: 'chips', colSpan: 1 },
             { key: 'summary', label: 'Summary', type: 'textarea', colSpan: 2 },
             { key: 'content', label: 'Full content (Markdown)', type: 'textarea', colSpan: 2 },
             F.image('banner_image', 'Banner image'),
             { key: 'published_at', label: 'Publish at', type: 'text', help: 'ISO 8601', colSpan: 1 },
             { key: 'author', label: 'Author', type: 'text', colSpan: 1 },
             { key: 'language', label: 'Language', type: 'text', colSpan: 1 },
             { key: 'exam_ids', label: 'Relevant exams', type: 'chips', colSpan: 2 },
             F.seo, F.visibility, F.displayOrder, F.active],
    extraColumns: [{ key: 'category', label: 'Category' }, { key: 'author', label: 'Author' }],
  },
  digital_notes: {
    title: 'Digital Notes', icon: 'reader', clientBadge: 'both',
    helpNote: 'Rich-text or PDF notes attached to subjects/chapters. Free or paywalled.',
    fields: [F.title, { key: 'subject_id', label: 'Subject ID', type: 'text', colSpan: 1 },
             { key: 'chapter_id', label: 'Chapter ID', type: 'text', colSpan: 1 },
             { key: 'exam_ids', label: 'Applicable exams', type: 'chips', colSpan: 2 },
             { key: 'product_ids', label: 'Attached to products', type: 'chips', colSpan: 2 },
             { key: 'pdf_url', label: 'PDF URL', type: 'url', colSpan: 2 },
             { key: 'content_md', label: 'Markdown content', type: 'textarea', colSpan: 2 },
             { key: 'language', label: 'Language', type: 'text', colSpan: 1 },
             { key: 'author', label: 'Author', type: 'text', colSpan: 1 },
             { key: 'is_free', label: 'Is free', type: 'bool', colSpan: 1 },
             F.displayOrder, F.active],
    extraColumns: [{ key: 'subject_id', label: 'Subject' }, { key: 'is_free', label: 'Free', format: (v) => (v ? 'Yes' : 'No') }],
  },
  previous_papers: {
    title: 'Previous Year Papers', icon: 'file-tray-full', clientBadge: 'both',
    helpNote: 'PYQs with answer keys + solutions. Powers the "25k+ PYP" claim in Test Prime.',
    fields: [F.title, { key: 'exam_id', label: 'Exam ID', type: 'text', required: true, colSpan: 1 },
             { key: 'year', label: 'Year', type: 'number', colSpan: 1 },
             { key: 'shift', label: 'Shift', type: 'text', colSpan: 1 },
             { key: 'duration_min', label: 'Duration (min)', type: 'number', colSpan: 1 },
             { key: 'total_marks', label: 'Total marks', type: 'number', colSpan: 1 },
             { key: 'questions_count', label: '# Questions', type: 'number', colSpan: 1 },
             { key: 'pdf_url', label: 'Paper PDF URL', type: 'url', colSpan: 2 },
             { key: 'answer_key_url', label: 'Answer key URL', type: 'url', colSpan: 2 },
             { key: 'solution_pdf_url', label: 'Solution PDF URL', type: 'url', colSpan: 2 },
             { key: 'language', label: 'Language', type: 'text', colSpan: 1 },
             { key: 'is_free', label: 'Is free', type: 'bool', colSpan: 1 },
             F.displayOrder, F.active],
    extraColumns: [{ key: 'exam_id', label: 'Exam' }, { key: 'year', label: 'Year' }],
  },

  // ==================== CONTENT MANAGEMENT ====================
  cms_web_pages: {
    title: 'Website CMS — Pages', icon: 'globe', clientBadge: 'website',
    helpNote: 'Every page on avision.co.in. Blocks = ordered array of section props consumed by future website frontend.',
    fields: [F.slug, F.title,
             { key: 'template', label: 'Template', type: 'select', options: [{ label: 'Home', value: 'home' }, { label: 'Standard', value: 'standard' }, { label: 'Landing', value: 'landing' }, { label: 'Legal', value: 'legal' }], colSpan: 1 },
             { key: 'language', label: 'Language', type: 'text', colSpan: 1 },
             { key: 'blocks', label: 'Blocks (JSON)', type: 'json', help: '[{"type":"hero","props":{…}}, {"type":"featured_courses"}, …]', colSpan: 2 },
             F.seo,
             { key: 'published', label: 'Published', type: 'bool', colSpan: 1 },
             F.displayOrder, F.active],
    primaryLabel: 'title',
    extraColumns: [{ key: 'slug', label: 'Slug' }, { key: 'template', label: 'Template' }],
  },
  cms_app_pages: {
    title: 'App CMS — Screens', icon: 'phone-portrait', clientBadge: 'app',
    helpNote: 'Native app home/section layouts. Slug=home controls the main home screen configuration.',
    fields: [F.slug, F.title,
             { key: 'template', label: 'Template', type: 'select', options: [{ label: 'Home v2', value: 'home_v2' }, { label: 'Category page', value: 'category' }, { label: 'Landing', value: 'landing' }], colSpan: 1 },
             { key: 'language', label: 'Language', type: 'text', colSpan: 1 },
             { key: 'blocks', label: 'Blocks (JSON)', type: 'json', help: '[{"type":"banner_slider"},{"type":"quick_access"},…]', colSpan: 2 },
             { key: 'published', label: 'Published', type: 'bool', colSpan: 1 },
             F.displayOrder, F.active],
    primaryLabel: 'title',
    extraColumns: [{ key: 'slug', label: 'Slug' }, { key: 'template', label: 'Template' }],
  },
  banners_home: {
    title: 'Home Banners', icon: 'image', clientBadge: 'both',
    helpNote: 'Sliding hero banners on App home + Website home. Server-side date-gated.',
    fields: [F.title, { key: 'subtitle', label: 'Subtitle', type: 'text', colSpan: 1 },
             F.image('image', 'Banner image URL'),
             { key: 'gradient', label: 'Gradient (JSON array)', type: 'json', placeholder: '["#0B4DB8", "#0EA5E9"]', colSpan: 1 },
             { key: 'cta_label', label: 'CTA label', type: 'text', colSpan: 1 },
             { key: 'cta_url', label: 'CTA URL', type: 'url', colSpan: 1 },
             { key: 'position', label: 'Position (top|inline)', type: 'text', colSpan: 1 },
             { key: 'start_at', label: 'Start at (ISO)', type: 'text', colSpan: 1 },
             { key: 'end_at', label: 'End at (ISO)', type: 'text', colSpan: 1 },
             F.visibility, F.displayOrder, F.active],
    extraColumns: [{ key: 'cta_url', label: 'CTA' }],
  },
  banners_promo: {
    title: 'Promotional Banners', icon: 'megaphone', clientBadge: 'both',
    helpNote: 'Sale/promo cards. Auto-hidden after end_at.',
    fields: [F.title, { key: 'subtitle', label: 'Subtitle', type: 'text', colSpan: 1 },
             F.image('image', 'Image URL'),
             { key: 'cta_label', label: 'CTA label', type: 'text', colSpan: 1 },
             { key: 'cta_url', label: 'CTA URL', type: 'url', colSpan: 1 },
             { key: 'kind', label: 'Kind', type: 'select', options: [{ label: 'Sale', value: 'sale' }, { label: 'Coupon', value: 'coupon' }, { label: 'Feature', value: 'feature' }], colSpan: 1 },
             { key: 'target_audience', label: 'Audience', type: 'text', help: 'category / all', colSpan: 1 },
             { key: 'start_at', label: 'Start at (ISO)', type: 'text', colSpan: 1 },
             { key: 'end_at', label: 'End at (ISO)', type: 'text', colSpan: 1 },
             F.visibility, F.displayOrder, F.active],
    extraColumns: [{ key: 'kind', label: 'Kind' }],
  },
  notifications: {
    title: 'Notifications', icon: 'notifications', clientBadge: 'both',
    helpNote: 'In-app announcements. Toggle Send push to deliver via Emergent push after publishing to the store.',
    fields: [F.title, { key: 'body', label: 'Body', type: 'textarea', colSpan: 2 },
             { key: 'kind', label: 'Kind', type: 'select', options: [{ label: 'Batch launch', value: 'batch_launch' }, { label: 'Announcement', value: 'announcement' }, { label: 'Discount', value: 'discount' }, { label: 'Result', value: 'result' }, { label: 'System', value: 'system' }], colSpan: 1 },
             { key: 'audience', label: 'Audience', type: 'text', help: 'all | banking | ssc | etc', colSpan: 1 },
             { key: 'target_url', label: 'Target URL', type: 'url', colSpan: 2 },
             F.image('banner_image', 'Banner image'),
             { key: 'icon', label: 'Icon key', type: 'text', colSpan: 1 },
             { key: 'send_push', label: 'Send push', type: 'bool', colSpan: 1 },
             F.displayOrder, F.active],
    extraColumns: [{ key: 'kind', label: 'Kind' }, { key: 'audience', label: 'Audience' }],
  },
  testimonials: {
    title: 'Testimonials', icon: 'star', clientBadge: 'both',
    helpNote: 'Selection stories shown on Website + App landing pages.',
    fields: [F.name, F.image('photo', 'Photo URL'),
             { key: 'exam_id', label: 'Exam ID', type: 'text', colSpan: 1 },
             { key: 'exam_name', label: 'Exam name', type: 'text', colSpan: 1 },
             { key: 'rank', label: 'Rank', type: 'number', colSpan: 1 },
             { key: 'year', label: 'Year', type: 'number', colSpan: 1 },
             { key: 'quote', label: 'Quote', type: 'textarea', required: true, colSpan: 2 },
             { key: 'video_url', label: 'Video URL', type: 'url', colSpan: 2 },
             { key: 'language', label: 'Language', type: 'text', colSpan: 1 },
             F.visibility, F.displayOrder, F.active],
    extraColumns: [{ key: 'exam_name', label: 'Exam' }, { key: 'rank', label: 'Rank' }],
  },
  results: {
    title: 'Results / Selections', icon: 'medal', clientBadge: 'both',
    helpNote: 'Public roll of honour. Feeds Website results page + App "Our Selections" carousel.',
    fields: [F.name, F.image('photo', 'Photo URL'),
             { key: 'exam_id', label: 'Exam ID', type: 'text', colSpan: 1 },
             { key: 'exam_name', label: 'Exam name', type: 'text', colSpan: 1 },
             { key: 'rank', label: 'Rank', type: 'number', colSpan: 1 },
             { key: 'year', label: 'Year', type: 'number', colSpan: 1 },
             { key: 'post', label: 'Post', type: 'text', colSpan: 1 },
             { key: 'batch', label: 'Batch', type: 'text', colSpan: 1 },
             { key: 'centre_id', label: 'Centre ID', type: 'text', colSpan: 1 },
             F.visibility, F.displayOrder, F.active],
    extraColumns: [{ key: 'exam_name', label: 'Exam' }, { key: 'rank', label: 'Rank' }, { key: 'year', label: 'Year' }],
  },
  faqs: {
    title: 'FAQs', icon: 'help-buoy', clientBadge: 'both',
    helpNote: 'Frequently asked questions. Sections: general | test-prime | live | video | payments.',
    fields: [{ key: 'question', label: 'Question', type: 'textarea', required: true, colSpan: 2 },
             { key: 'answer', label: 'Answer', type: 'textarea', required: true, colSpan: 2 },
             { key: 'section', label: 'Section', type: 'select', options: [{ label: 'General', value: 'general' }, { label: 'Test Prime', value: 'test-prime' }, { label: 'Live', value: 'live' }, { label: 'Video', value: 'video' }, { label: 'Payments', value: 'payments' }], colSpan: 1 },
             { key: 'product_id', label: 'Product ID (optional)', type: 'text', colSpan: 1 },
             { key: 'language', label: 'Language', type: 'text', colSpan: 1 },
             F.visibility, F.displayOrder, F.active],
    primaryLabel: 'question',
    extraColumns: [{ key: 'section', label: 'Section' }],
  },

  // ==================== ORGANISATION ====================
  franchises: {
    title: 'Franchise Master', icon: 'business', clientBadge: 'both',
    helpNote: 'Franchise partners. Each franchise can own multiple Centres. Powers Franchise-wise reports.',
    fields: [F.name,
             { key: 'code', label: 'Code (unique)', type: 'text', colSpan: 1 },
             { key: 'status', label: 'Status', type: 'select', options: [{ label: 'Active', value: 'active' }, { label: 'Paused', value: 'paused' }, { label: 'Closed', value: 'closed' }], colSpan: 1 },
             { key: 'franchisee_name', label: 'Franchisee name', type: 'text', colSpan: 1 },
             { key: 'franchisee_email', label: 'Franchisee email', type: 'text', colSpan: 1 },
             { key: 'franchisee_phone', label: 'Franchisee phone', type: 'text', colSpan: 1 },
             { key: 'gst', label: 'GST #', type: 'text', colSpan: 1 },
             { key: 'city', label: 'City', type: 'text', colSpan: 1 },
             { key: 'state', label: 'State', type: 'text', colSpan: 1 },
             { key: 'pincode', label: 'Pincode', type: 'text', colSpan: 1 },
             { key: 'address', label: 'Address', type: 'textarea', colSpan: 2 },
             { key: 'commission_pct', label: 'Commission %', type: 'number', colSpan: 1 },
             { key: 'revenue_share_pct', label: 'Revenue share %', type: 'number', colSpan: 1 },
             { key: 'started_at', label: 'Started at (ISO)', type: 'text', colSpan: 1 },
             { key: 'notes', label: 'Internal notes', type: 'textarea', colSpan: 2 },
             F.active],
    extraColumns: [{ key: 'city', label: 'City' }, { key: 'state', label: 'State' }, { key: 'status', label: 'Status' }],
  },
  centres_v2: {
    title: 'Centre Management', icon: 'storefront', clientBadge: 'both',
    helpNote: 'Physical centres — own or franchise-owned. Enhanced beyond legacy /admin/centres.',
    fields: [F.name,
             { key: 'code', label: 'Code (unique)', type: 'text', colSpan: 1 },
             { key: 'type', label: 'Type', type: 'select', options: [{ label: 'Own', value: 'own' }, { label: 'Franchise', value: 'franchise' }], colSpan: 1 },
             { key: 'franchise_id', label: 'Franchise ID', type: 'text', help: 'if type=franchise', colSpan: 1 },
             { key: 'status', label: 'Status', type: 'select', options: [{ label: 'Active', value: 'active' }, { label: 'Closed', value: 'closed' }], colSpan: 1 },
             { key: 'city', label: 'City', type: 'text', colSpan: 1 },
             { key: 'state', label: 'State', type: 'text', colSpan: 1 },
             { key: 'pincode', label: 'Pincode', type: 'text', colSpan: 1 },
             { key: 'phone', label: 'Phone', type: 'text', colSpan: 1 },
             { key: 'address', label: 'Address', type: 'textarea', colSpan: 2 },
             { key: 'manager_name', label: 'Manager name', type: 'text', colSpan: 1 },
             { key: 'manager_email', label: 'Manager email', type: 'text', colSpan: 1 },
             { key: 'seats', label: 'Seats', type: 'number', colSpan: 1 },
             { key: 'opened_at', label: 'Opened at (ISO)', type: 'text', colSpan: 1 },
             { key: 'notes', label: 'Notes', type: 'textarea', colSpan: 2 },
             F.active],
    extraColumns: [{ key: 'type', label: 'Type' }, { key: 'city', label: 'City' }, { key: 'status', label: 'Status' }],
  },
};
